// Generated by gencpp from file package_joystick/joy.msg
// DO NOT EDIT!


#ifndef PACKAGE_JOYSTICK_MESSAGE_JOY_H
#define PACKAGE_JOYSTICK_MESSAGE_JOY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package_joystick
{
template <class ContainerAllocator>
struct joy_
{
  typedef joy_<ContainerAllocator> Type;

  joy_()
    : posisi_y(0)  {
    }
  joy_(const ContainerAllocator& _alloc)
    : posisi_y(0)  {
  (void)_alloc;
    }



   typedef int16_t _posisi_y_type;
  _posisi_y_type posisi_y;





  typedef boost::shared_ptr< ::package_joystick::joy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package_joystick::joy_<ContainerAllocator> const> ConstPtr;

}; // struct joy_

typedef ::package_joystick::joy_<std::allocator<void> > joy;

typedef boost::shared_ptr< ::package_joystick::joy > joyPtr;
typedef boost::shared_ptr< ::package_joystick::joy const> joyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package_joystick::joy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package_joystick::joy_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package_joystick::joy_<ContainerAllocator1> & lhs, const ::package_joystick::joy_<ContainerAllocator2> & rhs)
{
  return lhs.posisi_y == rhs.posisi_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package_joystick::joy_<ContainerAllocator1> & lhs, const ::package_joystick::joy_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package_joystick

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package_joystick::joy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package_joystick::joy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_joystick::joy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_joystick::joy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_joystick::joy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_joystick::joy_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package_joystick::joy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2ddef0f714ebbf16e9d317effdce83d";
  }

  static const char* value(const ::package_joystick::joy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2ddef0f714ebbf1ULL;
  static const uint64_t static_value2 = 0x6e9d317effdce83dULL;
};

template<class ContainerAllocator>
struct DataType< ::package_joystick::joy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package_joystick/joy";
  }

  static const char* value(const ::package_joystick::joy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package_joystick::joy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 posisi_y\n"
;
  }

  static const char* value(const ::package_joystick::joy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package_joystick::joy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.posisi_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package_joystick::joy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package_joystick::joy_<ContainerAllocator>& v)
  {
    s << indent << "posisi_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.posisi_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_JOYSTICK_MESSAGE_JOY_H
