// Generated by gencpp from file package_tiga/joystick_pos.msg
// DO NOT EDIT!


#ifndef PACKAGE_TIGA_MESSAGE_JOYSTICK_POS_H
#define PACKAGE_TIGA_MESSAGE_JOYSTICK_POS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package_tiga
{
template <class ContainerAllocator>
struct joystick_pos_
{
  typedef joystick_pos_<ContainerAllocator> Type;

  joystick_pos_()
    : xFixMap(0)
    , yFixMap(0)  {
    }
  joystick_pos_(const ContainerAllocator& _alloc)
    : xFixMap(0)
    , yFixMap(0)  {
  (void)_alloc;
    }



   typedef int16_t _xFixMap_type;
  _xFixMap_type xFixMap;

   typedef int16_t _yFixMap_type;
  _yFixMap_type yFixMap;





  typedef boost::shared_ptr< ::package_tiga::joystick_pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package_tiga::joystick_pos_<ContainerAllocator> const> ConstPtr;

}; // struct joystick_pos_

typedef ::package_tiga::joystick_pos_<std::allocator<void> > joystick_pos;

typedef boost::shared_ptr< ::package_tiga::joystick_pos > joystick_posPtr;
typedef boost::shared_ptr< ::package_tiga::joystick_pos const> joystick_posConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package_tiga::joystick_pos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package_tiga::joystick_pos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package_tiga::joystick_pos_<ContainerAllocator1> & lhs, const ::package_tiga::joystick_pos_<ContainerAllocator2> & rhs)
{
  return lhs.xFixMap == rhs.xFixMap &&
    lhs.yFixMap == rhs.yFixMap;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package_tiga::joystick_pos_<ContainerAllocator1> & lhs, const ::package_tiga::joystick_pos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package_tiga

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package_tiga::joystick_pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package_tiga::joystick_pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_tiga::joystick_pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_tiga::joystick_pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_tiga::joystick_pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_tiga::joystick_pos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package_tiga::joystick_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0619210a7cf29ef0b55e827581daed4";
  }

  static const char* value(const ::package_tiga::joystick_pos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0619210a7cf29efULL;
  static const uint64_t static_value2 = 0x0b55e827581daed4ULL;
};

template<class ContainerAllocator>
struct DataType< ::package_tiga::joystick_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package_tiga/joystick_pos";
  }

  static const char* value(const ::package_tiga::joystick_pos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package_tiga::joystick_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 xFixMap\n"
"int16 yFixMap\n"
;
  }

  static const char* value(const ::package_tiga::joystick_pos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package_tiga::joystick_pos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xFixMap);
      stream.next(m.yFixMap);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joystick_pos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package_tiga::joystick_pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package_tiga::joystick_pos_<ContainerAllocator>& v)
  {
    s << indent << "xFixMap: ";
    Printer<int16_t>::stream(s, indent + "  ", v.xFixMap);
    s << indent << "yFixMap: ";
    Printer<int16_t>::stream(s, indent + "  ", v.yFixMap);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_TIGA_MESSAGE_JOYSTICK_POS_H
