// Generated by gencpp from file package_tiga/joystick.msg
// DO NOT EDIT!


#ifndef PACKAGE_TIGA_MESSAGE_JOYSTICK_H
#define PACKAGE_TIGA_MESSAGE_JOYSTICK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package_tiga
{
template <class ContainerAllocator>
struct joystick_
{
  typedef joystick_<ContainerAllocator> Type;

  joystick_()
    : posisi_x(0)
    , posisi_y(0)  {
    }
  joystick_(const ContainerAllocator& _alloc)
    : posisi_x(0)
    , posisi_y(0)  {
  (void)_alloc;
    }



   typedef int16_t _posisi_x_type;
  _posisi_x_type posisi_x;

   typedef int16_t _posisi_y_type;
  _posisi_y_type posisi_y;





  typedef boost::shared_ptr< ::package_tiga::joystick_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package_tiga::joystick_<ContainerAllocator> const> ConstPtr;

}; // struct joystick_

typedef ::package_tiga::joystick_<std::allocator<void> > joystick;

typedef boost::shared_ptr< ::package_tiga::joystick > joystickPtr;
typedef boost::shared_ptr< ::package_tiga::joystick const> joystickConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package_tiga::joystick_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package_tiga::joystick_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package_tiga::joystick_<ContainerAllocator1> & lhs, const ::package_tiga::joystick_<ContainerAllocator2> & rhs)
{
  return lhs.posisi_x == rhs.posisi_x &&
    lhs.posisi_y == rhs.posisi_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package_tiga::joystick_<ContainerAllocator1> & lhs, const ::package_tiga::joystick_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package_tiga

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package_tiga::joystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package_tiga::joystick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_tiga::joystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_tiga::joystick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_tiga::joystick_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_tiga::joystick_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package_tiga::joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6960680023b8cf73c32d80881e01cc9f";
  }

  static const char* value(const ::package_tiga::joystick_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6960680023b8cf73ULL;
  static const uint64_t static_value2 = 0xc32d80881e01cc9fULL;
};

template<class ContainerAllocator>
struct DataType< ::package_tiga::joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package_tiga/joystick";
  }

  static const char* value(const ::package_tiga::joystick_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package_tiga::joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 posisi_x\n"
"int16 posisi_y\n"
;
  }

  static const char* value(const ::package_tiga::joystick_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package_tiga::joystick_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.posisi_x);
      stream.next(m.posisi_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joystick_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package_tiga::joystick_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package_tiga::joystick_<ContainerAllocator>& v)
  {
    s << indent << "posisi_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.posisi_x);
    s << indent << "posisi_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.posisi_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_TIGA_MESSAGE_JOYSTICK_H
